### PR TITLE
Fix a compile error in tests 

### PR DESCRIPTION
**Pull request by damianb**
The express type augmentation was only updated for src/ and not for tests/ as well.  This updates the copy of express.d.ts to match src/.

### CODE REVIEW

**Comment by edking21** [comment]
Still unable to compile.  I got you changes to express.d.ts but still fails.
image

**Comment by damianb** [comment]
WOMM.

image

You're looking at the src/ copy of express.d.ts; verify that the copy in tests/express.d.ts is patched.

**Comment by damianb** [comment]
Bizarrely, the tests still run, but `tsc` is (rightly) complaining in vs code about the path to the ClientCertInfo interface.  Dropped another commit to fix it for accuracy's sake at minim.  Try now.

**Comment by edking21** [comment]
Reviewed and approved.  Compile error is fixed.

**Pull request merged**
