### PR TITLE
Log peer cert details

### LINKED ISSUE #17: Improve logging of peer certificate details
Currently, peer certificate details are omitted from a large chunk of our logging.  We should probably start including some portions in our request logging.

### PR DESCRIPTION
**Pull request by damianb**
Introduces logging for peer certificate details within requests; currently only logging the subjectaltname but this may expand depending on guidance and security requirements.  Closes #17.

### CODE REVIEW

**Comment by edking21** [comment]
Please click the Preview button to see a screen shot of the image.  The test on line 175 in server.spec.ts does not make sense.

image

**Comment by damianb** [comment]
Note that it is a check to validate that it does *not* equal the specified bad request id.  If it is working correctly, the service will have generated its own request ID instead.

**Comment by edking21** [comment]
I have reviewed the 15 commits and did not find any problems.

**Comment by damianb** [comment]
Keep in mind that this is a draft PR, which means it's a work in progress still.

Also, the list of commits is determined by the originating date of the branch; it is not necessarily the scope of the PR, as those commits may have been already merged by a prior PR.  Use the Files Changed tab to see the current scope of the changes in the PR.

**Comment by edking21** [comment]
Reviewed and approved 2 commits

**Pull request merged**
