### PR TITLE
Include request id responses

### LINKED ISSUE #6: Implement standardized logging
Standardized logging should be implemented throughout the service, logging to a file (location of file should be configurable at startup, possibly via config file).  

Any logging pertaining to a request should also include a `requestUUID` (presuming one is specified), which is specified within the request; this will allow traceability across multiple services, since one can search via the `requestUUID` across multiple services logs to gather information about any issues that occurred in relation to that request.

### PR DESCRIPTION
**Pull request by damianb**
Review #13 first - this PR depends on that PR being merged beforehand.

Closes #6, #12 .

Adds `chai-exclude` as a dependency, and updates tests so that they ignore the requestID returned.

### CODE REVIEW

**Comment by edking21** [comment]
Are we storing some logs as base64 and some as plain text?
Does a req.id with invalid characters indicate an injection attack of some sort and we have to generate our own req.id using uuid.generate?  If we have to review the logs at a later time and the logs contain uuid.generated req.id's will these req.id's stick out from the others?

**Comment by damianb** [comment]
To answer your questions: 

1. We are not storing the *logs* as b64; in the event we receive an invalid requestID, we are recording the originally specified request ID in base64 format to preserve it for future analysis, while also guarding against log injection attacks by not retaining the original format.  base64 encoding would prevent any useful injection attacks in this circumstance.

2. A req.id with invalid characters is not *always* indicative of an injection attack attempt (it's more likely going to be accidental), but a log injection attack would require specifying invalid characters as the requestID.  Should no requestID be provided or an invalid requestID be provided, we fall back to generating our own so we can trace through the logs.

3. To be honest, it doesn't matter whether our request IDs or externally specified request IDs stick out from one another; they just need to be consistent within our logs to allow us to trace an error or a request within our logs from source to sink.  The end goal is to allow GFM to take a requestID, either one we returned or one they specified to the service, and look in the logs to see what happened in regards to that request.

**Comment by edking21** [comment]
FYI: I had a previous government job where the requirement was to allow underscore in their id's.
GFM regex: [A-Za-z0-9-]
Others:        [A-Za-z0-9-_]   //note the added underscore

**Comment by edking21** [comment]
I have reviewed all 12 commits and did not see any problems based on my understanding of the code.

**Pull request merged**
